# Generated by Django 4.2 on 2026-04-02 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('content_type', models.CharField(choices=[('blog', 'Blog'), ('image', 'Image Story'), ('event', 'Event')], default='blog', max_length=20)),
                ('excerpt', models.CharField(max_length=280)),
                ('content', models.TextField(help_text='Main body content shown on the public detail page.')),
                ('cover_image', models.ImageField(blank=True, help_text='Recommended for homepage previews and image-based updates.', null=True, upload_to='updates/')),
                ('image_alt_text', models.CharField(blank=True, max_length=160)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('event_start', models.DateTimeField(blank=True, null=True)),
                ('event_end', models.DateTimeField(blank=True, null=True)),
                ('featured_on_homepage', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
