# Generated by Django 4.2 on 2026-04-03 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_portalupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalupdate',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Optional YouTube link to embed on the public update page.'),
        ),
        migrations.CreateModel(
            name='PortalUpdateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='updates/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='employee.portalupdate')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortalUpdateAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='updates/attachments/')),
                ('title', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='employee.portalupdate')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
