# Generated by Django 4.2 on 2026-04-24 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_portalupdate_youtube_url_portalupdateimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='registration_method',
            field=models.CharField(choices=[('self', 'Self Registration'), ('admin', 'Admin Created'), ('partner', 'Partner Registration')], default='self', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('employee', 'Employee'), ('partner', 'Partner'), ('admin', 'Administrator')], default='student', max_length=20),
        ),
    ]
