# Generated by Django 4.2 on 2026-04-25 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_portal', '0016_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='agency_no',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='alternate_email',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='apply_as',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='china_employment_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='china_employment_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='china_institute_or_employer',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='chinese_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='chinese_proficiency',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='city_of_birth',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='contact_person_china_address',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='contact_person_china_email',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='contact_person_china_fax',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='contact_person_china_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='contact_person_china_tel',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='correspondence_address',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='country_of_birth',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='discipline_1',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='discipline_2',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='discipline_3',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='emergency_contact_address',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='emergency_contact_email',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='emergency_contact_gender',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='emergency_contact_relation',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='employment_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='employment_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='english_proficiency',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='english_test_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='ever_had_chinese_government_scholarship',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='ever_studied_or_worked_in_china',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='father_age',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='father_occupation',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='given_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_art_music_examples',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_articles_or_papers',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_chinese_language_certificate',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_csca_score_report',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_english_certificate',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_english_language_certificate',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_highest_education_certificate',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_highest_education_transcript',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_hsk_certificate',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_non_criminal_record',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_passport_home_page',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_physical_exam_record',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_pre_admission_letter',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_pre_admission_letter_document',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_reference_1',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_reference_2',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_study_plan',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_country',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_field_of_study',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_institute',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_level',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_qualification',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='highest_education_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='hsk_level',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='hsk_score',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='hsk_test_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='institute_preference_1',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='institute_preference_2',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='institute_preference_3',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='major_1',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='major_2',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='major_3',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='major_study_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='major_study_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='mother_age',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='mother_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='mother_occupation',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='native_language',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_country',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_field_of_study',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_institute',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_level',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_qualification',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_1_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_country',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_field_of_study',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_institute',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_level',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_qualification',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_education_2_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='passport_no',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='personal_email',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='personal_phone',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='preferred_teaching_language',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='previous_csc_end_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='previous_csc_institute_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='previous_csc_start_date',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='skype_no',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='spouse_age',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='spouse_name',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='spouse_occupation',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='title_position',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='wechat_id',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='work_engaged',
        ),
        migrations.AddField(
            model_name='application',
            name='employee_status_note',
            field=models.TextField(blank=True, help_text='Status feedback visible to the student and partner.'),
        ),
        migrations.AddField(
            model_name='application',
            name='official_admission_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('not_applied', 'Not Applied'), ('applied', 'Applied'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_documents_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_eligibility',
            field=models.CharField(blank=True, choices=[('', '---------'), ('eligible', 'Eligible'), ('not_eligible', 'Not Eligible')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_final_decision',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditional')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_visa_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('not_started', 'Not Started'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='accommodation_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='education_sponsor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='english_test_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='estimated_budget_usd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='full_name_passport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_academic_certificates',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_academic_transcripts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_cv_resume',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_english_test_results',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_financial_proof',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_health_insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_medical_condition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_passport_copy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_personal_statement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_recommendation_letters',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_valid_visa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='medical_condition_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='needs_special_assistance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='passport_issue_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='passport_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='place_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='preferred_intake',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='program_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='residential_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='scholarship_applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='scholarship_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='special_assistance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='valid_visa_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='whatsapp_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='english_test_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='english_test_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
