# Generated by Django 4.2 on 2026-04-25 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


LEGACY_SUPPLEMENTAL_FIELDS = [
    'agency_name',
    'agency_no',
    'alternate_email',
    'apply_as',
    'china_employment_end_date',
    'china_employment_start_date',
    'china_institute_or_employer',
    'chinese_name',
    'chinese_proficiency',
    'city_of_birth',
    'contact_person_china_address',
    'contact_person_china_email',
    'contact_person_china_fax',
    'contact_person_china_name',
    'contact_person_china_tel',
    'correspondence_address',
    'country_of_birth',
    'discipline_1',
    'discipline_2',
    'discipline_3',
    'emergency_contact_address',
    'emergency_contact_email',
    'emergency_contact_gender',
    'emergency_contact_name',
    'emergency_contact_phone',
    'emergency_contact_relation',
    'employer',
    'employment_end_date',
    'employment_start_date',
    'english_proficiency',
    'english_test_date',
    'ever_had_chinese_government_scholarship',
    'ever_studied_or_worked_in_china',
    'father_age',
    'father_name',
    'father_occupation',
    'given_name',
    'has_art_music_examples',
    'has_articles_or_papers',
    'has_chinese_language_certificate',
    'has_csca_score_report',
    'has_english_certificate',
    'has_english_language_certificate',
    'has_highest_education_certificate',
    'has_highest_education_transcript',
    'has_hsk_certificate',
    'has_non_criminal_record',
    'has_passport_home_page',
    'has_physical_exam_record',
    'has_pre_admission_letter',
    'has_pre_admission_letter_document',
    'has_reference_1',
    'has_reference_2',
    'has_study_plan',
    'highest_education_country',
    'highest_education_end_date',
    'highest_education_field_of_study',
    'highest_education_institute',
    'highest_education_level',
    'highest_education_qualification',
    'highest_education_start_date',
    'hsk_level',
    'hsk_score',
    'hsk_test_date',
    'institute_preference_1',
    'institute_preference_2',
    'institute_preference_3',
    'major_1',
    'major_2',
    'major_3',
    'major_study_end_date',
    'major_study_start_date',
    'marital_status',
    'mother_age',
    'mother_name',
    'mother_occupation',
    'native_language',
    'other_education_1_country',
    'other_education_1_end_date',
    'other_education_1_field_of_study',
    'other_education_1_institute',
    'other_education_1_level',
    'other_education_1_qualification',
    'other_education_1_start_date',
    'other_education_2_country',
    'other_education_2_end_date',
    'other_education_2_field_of_study',
    'other_education_2_institute',
    'other_education_2_level',
    'other_education_2_qualification',
    'other_education_2_start_date',
    'passport_no',
    'personal_email',
    'personal_phone',
    'preferred_teaching_language',
    'previous_csc_end_date',
    'previous_csc_institute_name',
    'previous_csc_start_date',
    'religion',
    'skype_no',
    'spouse_age',
    'spouse_name',
    'spouse_occupation',
    'surname',
    'title_position',
    'wechat_id',
    'work_engaged',
]


def drop_existing_legacy_columns(apps, schema_editor):
    table_name = 'student_portal_applicationsupplementalprofile'
    connection = schema_editor.connection

    with connection.cursor() as cursor:
        existing_columns = {
            column.name for column in connection.introspection.get_table_description(cursor, table_name)
        }

    quoted_table = schema_editor.quote_name(table_name)
    for column_name in LEGACY_SUPPLEMENTAL_FIELDS:
        if column_name not in existing_columns:
            continue
        quoted_column = schema_editor.quote_name(column_name)
        schema_editor.execute(f'ALTER TABLE {quoted_table} DROP COLUMN {quoted_column}')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_portal', '0016_alter_document_file'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_existing_legacy_columns, migrations.RunPython.noop),
            ],
            state_operations=[
                *[
                    migrations.RemoveField(
                        model_name='applicationsupplementalprofile',
                        name=field_name,
                    )
                    for field_name in LEGACY_SUPPLEMENTAL_FIELDS
                ],
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='employee_status_note',
            field=models.TextField(blank=True, help_text='Status feedback visible to the student and partner.'),
        ),
        migrations.AddField(
            model_name='application',
            name='official_admission_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('not_applied', 'Not Applied'), ('applied', 'Applied'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_documents_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_eligibility',
            field=models.CharField(blank=True, choices=[('', '---------'), ('eligible', 'Eligible'), ('not_eligible', 'Not Eligible')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_final_decision',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditional')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_visa_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('not_started', 'Not Started'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
