# Generated by Django 4.2 on 2026-04-25 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


LEGACY_SUPPLEMENTAL_FIELDS = [
    'agency_name',
    'agency_no',
    'alternate_email',
    'apply_as',
    'china_employment_end_date',
    'china_employment_start_date',
    'china_institute_or_employer',
    'chinese_name',
    'chinese_proficiency',
    'city_of_birth',
    'contact_person_china_address',
    'contact_person_china_email',
    'contact_person_china_fax',
    'contact_person_china_name',
    'contact_person_china_tel',
    'correspondence_address',
    'country_of_birth',
    'discipline_1',
    'discipline_2',
    'discipline_3',
    'emergency_contact_address',
    'emergency_contact_email',
    'emergency_contact_gender',
    'emergency_contact_name',
    'emergency_contact_phone',
    'emergency_contact_relation',
    'employer',
    'employment_end_date',
    'employment_start_date',
    'english_proficiency',
    'english_test_date',
    'ever_had_chinese_government_scholarship',
    'ever_studied_or_worked_in_china',
    'father_age',
    'father_name',
    'father_occupation',
    'given_name',
    'has_art_music_examples',
    'has_articles_or_papers',
    'has_chinese_language_certificate',
    'has_csca_score_report',
    'has_english_certificate',
    'has_english_language_certificate',
    'has_highest_education_certificate',
    'has_highest_education_transcript',
    'has_hsk_certificate',
    'has_non_criminal_record',
    'has_passport_home_page',
    'has_physical_exam_record',
    'has_pre_admission_letter',
    'has_pre_admission_letter_document',
    'has_reference_1',
    'has_reference_2',
    'has_study_plan',
    'highest_education_country',
    'highest_education_end_date',
    'highest_education_field_of_study',
    'highest_education_institute',
    'highest_education_level',
    'highest_education_qualification',
    'highest_education_start_date',
    'hsk_level',
    'hsk_score',
    'hsk_test_date',
    'institute_preference_1',
    'institute_preference_2',
    'institute_preference_3',
    'major_1',
    'major_2',
    'major_3',
    'major_study_end_date',
    'major_study_start_date',
    'marital_status',
    'mother_age',
    'mother_name',
    'mother_occupation',
    'native_language',
    'other_education_1_country',
    'other_education_1_end_date',
    'other_education_1_field_of_study',
    'other_education_1_institute',
    'other_education_1_level',
    'other_education_1_qualification',
    'other_education_1_start_date',
    'other_education_2_country',
    'other_education_2_end_date',
    'other_education_2_field_of_study',
    'other_education_2_institute',
    'other_education_2_level',
    'other_education_2_qualification',
    'other_education_2_start_date',
    'passport_no',
    'personal_email',
    'personal_phone',
    'preferred_teaching_language',
    'previous_csc_end_date',
    'previous_csc_institute_name',
    'previous_csc_start_date',
    'religion',
    'skype_no',
    'spouse_age',
    'spouse_name',
    'spouse_occupation',
    'surname',
    'title_position',
    'wechat_id',
    'work_engaged',
]


def rebuild_supplemental_profile_table(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    original_table = 'student_portal_applicationsupplementalprofile'
    backup_table = 'student_portal_applicationsupplementalprofile_legacy'

    existing_tables = set(connection.introspection.table_names())
    if original_table not in existing_tables and backup_table not in existing_tables:
        return

    if vendor != 'mysql':
        # The production failure is MySQL-specific. On other backends, keep the
        # migration state change only and avoid backend-specific table rebuilds.
        return

    source_table = original_table if original_table in existing_tables else backup_table
    quoted_original = schema_editor.quote_name(original_table)
    quoted_backup = schema_editor.quote_name(backup_table)

    with connection.cursor() as cursor:
        if source_table == original_table:
            if backup_table in existing_tables:
                schema_editor.execute(f'DROP TABLE {quoted_backup}')
            schema_editor.execute(f'RENAME TABLE {quoted_original} TO {quoted_backup}')
            source_table = backup_table

        source_columns = {
            column.name
            for column in connection.introspection.get_table_description(cursor, source_table)
        }

    schema_editor.execute(f'DROP TABLE IF EXISTS {quoted_original}')
    schema_editor.execute(
        f"""
        CREATE TABLE {quoted_original} (
            id BIGINT AUTO_INCREMENT PRIMARY KEY,
            application_id BIGINT NOT NULL UNIQUE,
            passport_expiration_date DATE NULL,
            english_test_name LONGTEXT NULL,
            english_test_score LONGTEXT NULL,
            has_passport_photo BOOL NULL,
            has_other_attachments BOOL NULL,
            other_attachments_description LONGTEXT NULL,
            declaration_agreed BOOL NULL,
            serial_number VARCHAR(100) NULL,
            generated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
            CONSTRAINT student_portal_appsup_profile_application_id_fk
                FOREIGN KEY (application_id)
                REFERENCES student_portal_application (id)
        ) ROW_FORMAT=DYNAMIC
        """
    )

    def select_expr(column_name, default_sql='NULL'):
        quoted = schema_editor.quote_name(column_name)
        return quoted if column_name in source_columns else default_sql

    insert_sql = f"""
        INSERT INTO {quoted_original} (
            id,
            application_id,
            passport_expiration_date,
            english_test_name,
            english_test_score,
            has_passport_photo,
            has_other_attachments,
            other_attachments_description,
            declaration_agreed,
            serial_number,
            generated_at
        )
        SELECT
            {select_expr('id')},
            {select_expr('application_id')},
            {select_expr('passport_expiration_date')},
            {select_expr('english_test_name')},
            {select_expr('english_test_score')},
            {select_expr('has_passport_photo')},
            {select_expr('has_other_attachments')},
            {select_expr('other_attachments_description')},
            {select_expr('declaration_agreed')},
            {select_expr('serial_number')},
            {select_expr('generated_at', 'CURRENT_TIMESTAMP(6)')}
        FROM {quoted_backup}
    """
    schema_editor.execute(insert_sql)
    schema_editor.execute(f'DROP TABLE {quoted_backup}')


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student_portal', '0016_alter_document_file'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rebuild_supplemental_profile_table, migrations.RunPython.noop),
            ],
            state_operations=[
                *[
                    migrations.RemoveField(
                        model_name='applicationsupplementalprofile',
                        name=field_name,
                    )
                    for field_name in LEGACY_SUPPLEMENTAL_FIELDS
                ],
            ],
        ),
        migrations.AddField(
            model_name='application',
            name='employee_status_note',
            field=models.TextField(blank=True, help_text='Status feedback visible to the student and partner.'),
        ),
        migrations.AddField(
            model_name='application',
            name='official_admission_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('not_applied', 'Not Applied'), ('applied', 'Applied'), ('offer_received', 'Offer Received'), ('accepted', 'Accepted')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_documents_verified',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_eligibility',
            field=models.CharField(blank=True, choices=[('', '---------'), ('eligible', 'Eligible'), ('not_eligible', 'Not Eligible')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_final_decision',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('conditional', 'Conditional')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='official_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='official_visa_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('not_started', 'Not Started'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_status_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
