# Generated by Django 4.2 on 2026-04-26 09:00

from django.db import migrations, models


def set_dynamic_row_format(apps, schema_editor):
    if schema_editor.connection.vendor != 'mysql':
        return
    schema_editor.execute(
        "ALTER TABLE student_portal_applicationsupplementalprofile ROW_FORMAT=DYNAMIC"
    )


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ('student_portal', '0017_remove_applicationsupplementalprofile_agency_name_and_more'),
    ]

    operations = [
        migrations.RunPython(set_dynamic_row_format, migrations.RunPython.noop),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='accommodation_preference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_postal_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_region',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='education_sponsor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='english_test_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='estimated_budget_usd',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='full_name_passport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_academic_certificates',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_academic_transcripts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_cv_resume',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_english_test_results',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_financial_proof',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_health_insurance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_medical_condition',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_passport_copy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_personal_statement',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_recommendation_letters',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='has_valid_visa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='medical_condition_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='needs_special_assistance',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='passport_issue_country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='passport_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_field_of_study',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_gpa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_year_completed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='place_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='preferred_intake',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='program_level',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='residential_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='scholarship_applied',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='scholarship_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='special_assistance_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='valid_visa_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='whatsapp_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='english_test_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='english_test_score',
            field=models.TextField(blank=True, null=True),
        ),
    ]
