# Generated by Django 4.2 on 2026-06-04 08:19

from django.db import migrations, models
import django.db.models.deletion


DYNAMIC_TABLES = (
    "student_portal_studentprofile",
    "student_portal_applicationsupplementalprofile",
    "student_portal_workexperience",
)


def _ensure_mysql_dynamic_row_format(apps, schema_editor):
    """Switch the wide tables to ROW_FORMAT=DYNAMIC on MySQL.

    MySQL/InnoDB stores variable-length columns inline up to a per-row
    budget (default 8126 bytes for COMPACT rows). With ~200 wide
    CharField columns and utf8mb4 we blow that budget. DYNAMIC row
    format allows long values to be stored off-page, so the on-page
    footprint per column is ~20 bytes regardless of the declared
    length. This is a no-op on non-MySQL backends.
    """
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in DYNAMIC_TABLES:
            cursor.execute(
                "SHOW TABLES LIKE %s",
                [table],
            )
            if not cursor.fetchone():
                continue
            cursor.execute(
                "SELECT CREATE_OPTIONS FROM information_schema.TABLES "
                "WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s",
                [table],
            )
            row = cursor.fetchone()
            create_options = (row[0] or "") if row else ""
            if "row_format=dynamic" in create_options.lower():
                continue
            try:
                cursor.execute(
                    f"ALTER TABLE `{table}` ROW_FORMAT=DYNAMIC"
                )
            except Exception:
                pass


def _restore_mysql_row_format(apps, schema_editor):
    """Reverse of ``_ensure_mysql_dynamic_row_format``.

    We don't force a specific row format on reversal because InnoDB's
    default is a sensible choice.  The function exists so Django has a
    matching reverse callable.
    """
    if schema_editor.connection.vendor != "mysql":
        return
    with schema_editor.connection.cursor() as cursor:
        for table in DYNAMIC_TABLES:
            cursor.execute("SHOW TABLES LIKE %s", [table])
            if not cursor.fetchone():
                continue
            try:
                cursor.execute(f"ALTER TABLE `{table}` ROW_FORMAT=COMPACT")
            except Exception:
                pass


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0018_add_awec_fields_to_supplemental_profile'),
    ]

    operations = [
        migrations.RunPython(
            code=_ensure_mysql_dynamic_row_format,
            reverse_code=_restore_mysql_row_format,
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_completed_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_start_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='bachelor_started_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_completed_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_start_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='certificate_started_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_address_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_address_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_district_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_duration_at_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_house_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_mtaa',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_nearest_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_neighbourhood',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_region_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_street',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_village',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_ward',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='current_ward_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_completed_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_start_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='diploma_started_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='english_is_primary_language',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='english_test_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_completed_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_start_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='master_started_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_address_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_address_status',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_district_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_duration_at_address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_house_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_mtaa',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_nearest_landmark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_neighbourhood',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_postal_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_region_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_street',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_village',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_ward',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='permanent_ward_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_completed_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_start_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='phd_started_year',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_certificate_awarded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_district_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_house_no',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_institution',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_mtaa',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_neighbourhood',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_region_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_street',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_ward',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='applicationsupplementalprofile',
            name='professional_qualification_ward_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_completed_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_start_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_started_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_street_village',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_street_village',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='house_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('', '---------'), ('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_postal_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_street_village',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='native_language',
            field=models.CharField(blank=True, default='Swahili', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_completed_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_start_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_started_year',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_date_of_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_date_of_issue',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_issue_country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='passport_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='village',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='district',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='district_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='house_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='mtaa',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='place_neighbourhood',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='region',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='region_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='street',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='supervisor',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='supervisor_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='ward',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='ward_post_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='accommodation_preference',
            field=models.CharField(blank=True, choices=[('', '---------'), ('university_dormitory', 'University Dormitory'), ('private_apartment', 'Private Apartment'), ('homestay', 'Homestay'), ('not_required', 'Not Required')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='current_city',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='current_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='current_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='preferred_intake',
            field=models.CharField(blank=True, choices=[('', '---------'), ('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='applicationsupplementalprofile',
            name='program_level',
            field=models.CharField(blank=True, choices=[('', '---------'), ('certificate', 'Certificate'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor Degree'), ('master', 'Master Degree'), ('phd', 'PhD'), ('language', 'Language Program'), ('foundation', 'Foundation Program'), ('short_course', 'Short Course')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport Copy'), ('passport_photo', 'Passport Photo'), ('ordinary_level', 'Ordinary Level Certificate'), ('advanced_level', 'Advanced Level Certificate'), ('academic_transcript', 'Academic Transcript'), ('degree_certificate', 'Degree / Diploma Certificate'), ('application_form', 'Application Form'), ('recommendation_letter', 'Recommendation Letter'), ('sop', 'Statement of Purpose / Motivation Letter'), ('cv', 'CV / Resume'), ('language_test', 'English Proficiency Test (IELTS / TOEFL)'), ('proof_of_funds', 'Proof of Funds'), ('health_insurance', 'Health Insurance'), ('financial_documents', 'Financial Documents (Legacy)'), ('other', 'Other Document')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_program_1',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_program_2',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_program_3',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='preferred_program_4',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.CreateModel(
            name='ProfessionalQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveSmallIntegerField(default=1, help_text='Use 1, 2 or 3 only')),
                ('qualification_title', models.CharField(blank=True, max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255)),
                ('institution_address', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, default='Tanzania', max_length=100)),
                ('period', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('finished_date', models.DateField(blank=True, null=True)),
                ('award_certificate', models.CharField(blank=True, choices=[('', '---------'), ('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('region', models.CharField(blank=True, max_length=120)),
                ('district', models.CharField(blank=True, max_length=120)),
                ('ward', models.CharField(blank=True, max_length=120)),
                ('street', models.CharField(blank=True, max_length=180)),
                ('mtaa', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_qualification_entries', to='student_portal.application')),
            ],
            options={
                'verbose_name': 'Professional Qualification',
                'verbose_name_plural': 'Professional Qualifications',
                'ordering': ['order_number', 'id'],
                'unique_together': {('application', 'order_number')},
            },
        ),
    ]
