# Generated by Django 4.2 on 2026-06-08 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0022_normalize_student_profile_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
