# Generated by Django 4.2 on 2026-06-17 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0023_application_reference_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='country',
        ),
        migrations.RemoveField(
            model_name='application',
            name='course',
        ),
        migrations.RemoveField(
            model_name='application',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_school_mtaa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_gender',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_mtaa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_mtaa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_mtaa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_country',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_school_mtaa',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_country_4',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='preferred_program_4',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='whatsapp_number',
        ),
    ]
