# Generated by Django 4.2 on 2026-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0024_remove_application_application_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='alevel_region',
            new_name='alevel_certificate_no',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='olevel_region',
            new_name='alevel_exam_board',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='emergency_address',
            new_name='alevel_remarks',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='father_address',
            new_name='emergency_remarks',
        ),
        migrations.RenameField(
            model_name='studentprofile',
            old_name='mother_address',
            new_name='olevel_remarks',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_school_neighbourhood',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_started_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_street',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='alevel_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_neighbourhood',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='emergency_street_village',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_neighbourhood',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_postal_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='father_street_village',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_neighbourhood',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_postal_code',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mother_street_village',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_address',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_school_neighbourhood',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_started_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_street',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='olevel_year',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_date_of_expiry',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_date_of_issue',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_expired_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_expiry_date',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='passport_issued_date',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='alevel_school_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_alternative_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='emergency_relationship_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='father_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='mother_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_certificate_no',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_exam_board',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='olevel_school_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='preferred_intake',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
