# Generated by Django 4.2 on 2026-06-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0025_rename_alevel_region_studentprofile_alevel_certificate_no_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='whatsapp_number',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
