# Generated by Django 4.2 on 2026-06-29 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0026_remove_whatsapp_number_from_supplemental_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsupplementaladdress',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='current_post_code',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='permanent_post_code',
        ),
        migrations.RemoveField(
            model_name='studentaddress',
            name='post_code',
        ),
    ]
