# Generated by Django 4.2 on 2026-06-29 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0027_fix_duplicate_post_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_academic_certificates',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_academic_transcripts',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_cv_resume',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_english_test_results',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_financial_proof',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_health_insurance',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_other_attachments',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_passport_copy',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_passport_photo',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_personal_statement',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='has_recommendation_letters',
        ),
        migrations.RemoveField(
            model_name='applicationsupplementalprofile',
            name='other_attachments_description',
        ),
    ]
