# Generated by Django 5.2 on 2026-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0028_remove_applicationsupplementalprofile_has_academic_certificates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='current_step',
            field=models.CharField(blank=True, help_text='Last completed step name for draft resumption', max_length=50, null=True),
        ),
    ]
