# Generated by Django 5.2 on 2026-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0030_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='alevel_gpa',
            field=models.CharField(blank=True, choices=[('Division I', 'Division I'), ('Division II', 'Division II'), ('Division III', 'Division III'), ('Division IV', 'Division IV'), ('Zero', 'Zero')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='olevel_gpa',
            field=models.CharField(blank=True, choices=[('Division I', 'Division I'), ('Division II', 'Division II'), ('Division III', 'Division III'), ('Division IV', 'Division IV'), ('Zero', 'Zero')], max_length=20),
        ),
    ]
