# Generated by Django 4.2 on 2026-04-24 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_portal', '0012_workexperience'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('global_agency', '0007_alter_studentapplication_emergency_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='portal_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_intakes', to='student_portal.application'),
        ),
    ]
