# Generated by Django 4.2 on 2026-06-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0010_remove_studentapplication_fields_not_in_pdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentapplication',
            old_name='alevel_year',
            new_name='alevel_completed_year',
        ),
        migrations.RenameField(
            model_name='studentapplication',
            old_name='olevel_year',
            new_name='alevel_start_year',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='alevel_address',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='emergency_address',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='olevel_address',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='alevel_certificate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='alevel_exam_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='alevel_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='alevel_school_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='emergency_alternative_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='emergency_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='emergency_relationship_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='emergency_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='father_place_neighbourhood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='father_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='father_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='marital_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mother_place_neighbourhood',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mother_relationship',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mother_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='native_language',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='olevel_certificate_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='olevel_completed_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='olevel_exam_board',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='olevel_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='olevel_school_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='olevel_start_year',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='place_of_birth',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='preferred_intake',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
