# Generated by Django 4.2 on 2026-06-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0011_rename_alevel_year_studentapplication_alevel_completed_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='heard_about_other',
            field=models.TextField(blank=True, null=True),
        ),
    ]
