# Generated by Django 4.2 on 2026-06-25 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0012_alter_studentapplication_heard_about_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='declaration_applicant_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='declaration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='declaration_signature_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='office_approval_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='office_director_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='office_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_award_certificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_institution_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_award_certificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_institution_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_award_certificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_finished_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_institution_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_period',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='profq3_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_district_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_region_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_street',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_supervisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_ward',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_ward_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_worked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work1_worked_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_country',
            field=models.CharField(blank=True, default='Tanzania', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_district',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_district_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_duties',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_position',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_region',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_region_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_street',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_supervisor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_ward',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_ward_post_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_worked_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='work2_worked_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
