# Generated by Django 4.2 on 2026-06-26 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0013_add_blank_form_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
