# Generated by Django 5.2 on 2026-06-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0014_contactmessage_is_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='current_step',
            field=models.IntegerField(default=0, help_text='Last completed wizard step index (0 = not started)'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Whether this is an in-progress draft or finalized submission'),
        ),
    ]
