# Generated by Django 5.2 on 2026-07-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_agency', '0015_studentapplication_current_step_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='alevel_gpa',
            field=models.CharField(blank=True, choices=[('Division I', 'Division I'), ('Division II', 'Division II'), ('Division III', 'Division III'), ('Division IV', 'Division IV'), ('Zero', 'Zero')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='olevel_gpa',
            field=models.CharField(blank=True, choices=[('Division I', 'Division I'), ('Division II', 'Division II'), ('Division III', 'Division III'), ('Division IV', 'Division IV'), ('Zero', 'Zero')], max_length=20, null=True),
        ),
    ]
