"""
Security utilities for the project.

This module provides helpers for:
- Webhook signature verification (HMAC-SHA256) for payment providers
- URL safety validation to prevent javascript: and other XSS schemes in href
- Safe anchor link rendering
"""

import hashlib
import hmac
import logging
from typing import Optional
from urllib.parse import urlparse

from django.conf import settings

logger = logging.getLogger(__name__)


SAFE_URL_SCHEMES = frozenset({'http', 'https', 'mailto', 'tel'})
ALLOWED_MEDIA_PREFIXES = ('/media/', '/static/', settings.MEDIA_URL, settings.STATIC_URL)


def is_safe_url_scheme(url: str, allowed_schemes: Optional[frozenset] = None) -> bool:
    """
    Return True only if *url* uses a safe scheme (http, https, mailto, tel) and
    has a host component. Defends against ``javascript:``, ``data:`` and other
    attacker-controlled href values.
    """
    if not url or not isinstance(url, str):
        return False

    allowed = allowed_schemes or SAFE_URL_SCHEMES
    try:
        parsed = urlparse(url.strip())
    except (ValueError, TypeError):
        return False

    if parsed.scheme.lower() not in allowed:
        return False

    if parsed.scheme.lower() in {'http', 'https'} and not parsed.netloc:
        return False

    return True


def is_safe_internal_url(url: str) -> bool:
    """
    Return True if *url* is a same-site or relative path that does not
    carry an unsafe scheme. Useful for href values that may legitimately
    be relative (``/media/...``) or absolute paths generated by Django's
    storage backends.
    """
    if not url or not isinstance(url, str):
        return False

    stripped = url.strip()
    if not stripped:
        return False

    if stripped.startswith(('#', '?', '/')):
        return True

    if any(stripped.startswith(prefix) for prefix in ALLOWED_MEDIA_PREFIXES if prefix):
        return True

    return is_safe_url_scheme(stripped)


def safe_href(url: str, fallback: str = '#') -> str:
    """
    Return *url* unchanged when it is safe to embed in an ``href`` attribute,
    otherwise return *fallback*. Use this in Python code before passing a
    user-controlled URL to a template, or as a defensive default in
    JavaScript.
    """
    return url if is_safe_internal_url(url) else fallback


def verify_webhook_signature(
    payload: bytes,
    signature_header: Optional[str],
    secret: str,
    tolerance_seconds: int = 300,
    timestamp_header: Optional[str] = None,
):
    """
    Verify an HMAC-SHA256 webhook signature.

    The signature header is expected to be hex-encoded and may optionally be
    prefixed with ``sha256=`` (Stripe / GitHub style). The optional timestamp
    header lets callers reject stale replays.

    Returns ``True`` when the signature matches *payload* and *secret*, and
    the timestamp (if supplied) is within *tolerance_seconds* of ``now``.
    Returns ``False`` on any mismatch or malformed input.
    """
    if not signature_header or not secret:
        return False

    try:
        signature_value = signature_header.strip()
        if signature_value.startswith('sha256='):
            signature_value = signature_value.split('=', 1)[1]

        provided = bytes.fromhex(signature_value)
    except (ValueError, AttributeError):
        return False

    expected = hmac.new(
        secret.encode('utf-8'),
        payload,
        hashlib.sha256,
    ).digest()

    if not hmac.compare_digest(provided, expected):
        return False

    if timestamp_header is not None:
        try:
            ts = int(timestamp_header)
        except (TypeError, ValueError):
            return False

        import time
        if abs(time.time() - ts) > tolerance_seconds:
            return False

    return True


def get_clickpesa_webhook_secret() -> str:
    """
    Return the ClickPesa webhook secret. Prefer ``CLICKPESA_WEBHOOK_SECRET``
    but fall back to the existing ``CLICKPESA_CHECKSUM`` so existing
    installations keep working until they rotate to the dedicated secret.
    """
    return getattr(settings, 'CLICKPESA_WEBHOOK_SECRET', '') or getattr(
        settings, 'CLICKPESA_CHECKSUM', ''
    )
